from pathlib import Path

import pytest

from scripts.gen_env_example import generate_env_example, render_env_example

EXPECTED_ENV_EXAMPLE = """# Generated by scripts/gen_env_example.py from pocket.config.Settings.
# Do not add real secrets to this file.

# Pocket Agent model to use for generating responses.
POCKET_MODEL=

# Provider to use for generating responses.
POCKET_PROVIDER=ollama

# Home directory for Pocket Agent.
POCKET_HOME=.pocket

# Maximum number of iterations for generating responses.
POCKET_MAX_ITERATIONS=10

# API key for the provider.
POCKET_API_KEY=
"""


def test_render_env_example_is_deterministic_and_secret_safe(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("POCKET_API_KEY", "machine-secret-must-not-leak")

    rendered = render_env_example()

    assert rendered == EXPECTED_ENV_EXAMPLE
    assert "SecretStr" not in rendered
    assert "machine-secret-must-not-leak" not in rendered


def test_generate_env_example_writes_requested_path(tmp_path: Path) -> None:
    output_path = tmp_path / ".env.example"

    returned_path = generate_env_example(output_path)

    assert returned_path == output_path
    assert output_path.read_text(encoding="utf-8") == EXPECTED_ENV_EXAMPLE
