"""Generate the committed environment template from Settings metadata."""

from pathlib import Path
from types import UnionType
from typing import Union, get_args, get_origin

from pydantic import SecretStr
from pydantic_core import PydanticUndefined

from pocket.config import Settings

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / ".env.example"


def _is_secret(annotation: object) -> bool:
    """Return whether an annotation contains SecretStr."""
    origin = get_origin(annotation)
    return annotation is SecretStr or (
        origin in (Union, UnionType) and SecretStr in get_args(annotation)
    )


def _render_default(annotation: object, default: object) -> str:
    """Render a safe dotenv value without constructing Settings."""
    if _is_secret(annotation) or default in (None, PydanticUndefined):
        return ""
    if isinstance(default, bool):
        return str(default).lower()
    return str(default)


def render_env_example() -> str:
    """Build deterministic dotenv content from declared Settings fields."""
    prefix = str(Settings.model_config.get("env_prefix", ""))
    sections = [
        "# Generated by scripts/gen_env_example.py from pocket.config.Settings.",
        "# Do not add real secrets to this file.",
    ]

    for name, field in Settings.model_fields.items():
        description = field.description or name.replace("_", " ").capitalize()
        env_name = f"{prefix}{name}".upper()
        value = _render_default(field.annotation, field.default)
        sections.extend(("", f"# {description}", f"{env_name}={value}"))

    return "\n".join(sections) + "\n"


def generate_env_example(output_path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    """Write the generated template and return its destination."""
    output_path.write_text(render_env_example(), encoding="utf-8")
    return output_path


if __name__ == "__main__":
    generate_env_example()
